# Generated by Django 4.1.7 on 2023-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_remove_questionnaire_client_questionnaire_client_rep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
