# Generated by Django 4.1.7 on 2023-03-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_alter_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
