# Generated by Django 4.1.7 on 2023-03-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0004_alter_answer_answer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="author",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Sales Managers"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_manager_questionnaires",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaire",
            name="client_rep",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Corporate Client Representatives"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_rep_questionnaires",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionnaire_responses",
                to="feedback.questionnaire",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="respondent",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Corporate Client Representatives"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_rep_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
