# Generated by Django 4.1.7 on 2023-03-13 22:01

import feedback.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0006_monthlyfeedback_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlyfeedback",
            options={"verbose_name_plural": "Monthly feedback"},
        ),
        migrations.AlterField(
            model_name="monthlyfeedback",
            name="month",
            field=models.CharField(
                max_length=7, validators=[feedback.validators.validate_month_format]
            ),
        ),
    ]
