# Generated by Django 4.1.7 on 2023-03-13 22:32

import feedback.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0007_alter_monthlyfeedback_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyfeedback",
            name="month",
            field=models.CharField(
                default="2023-03",
                max_length=7,
                validators=[feedback.validators.validate_month_format],
            ),
        ),
    ]
